# Generated by Django 4.2.4 on 2024-11-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_accountdetail_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
